tasks:
  - init: yarn install && gp sync-done install
    command: yarn dev
  - init: gp sync-await install
    command: yarn storybook
ports:
  - port: 3000
    visibility: public
  - port: 8545
    visibility: public
  - port: 6006
    visibility: public
